# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:14.4.0-alpine

before_script:
  - npm install
  - npm run build

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - dist/

# Ensure correct code style
test:lint:
  script:
    - npm run lint

# Build documentation website
# pages:
#   stage: deploy
#   script: npm run docs:build
#   artifacts:
#     paths:
#     - public
#   only:
#    - tags

# Build and create artficats for master
build:
  stage: deploy
  artifacts:
    paths:
    - dist
  only:
    - master
  script:
    - npm run build
