name: pull-request
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Build
         uses: actions/setup-node@v1
         run: npm install
       - name: Archive Build
         uses: actions/upload-artifact@v3
         with:
            path: dist