name: merge
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Setup Build
         uses: actions/setup-node@v1

       - name: Install Dependencies
         run: npm install

       - name: Build
         run: npm build

       - name: Archive Build
         uses: actions/upload-artifact@v3
         with:
            path: dist