name: pull-request
on:
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Check out code
         uses: actions/checkout@v2
       - name: Setup Build
         uses: actions/setup-node@v1
       - name: Install Dependencies
         run: npm install
       - name: Build
         run: npm run build